### ISSUE TITLE
Citation information?

### ISSUE THREAD

**Issue by albertvillanova** [dumitrescustefan/RO-STS#4]
Is there any update in relation with your citation information?

Your license is CC BY-SA 4.0, but we don't know how to cite you.

Thank you.

**Comment by dumitrescustefan** [comment]
Hi, yes, sorry for the delay, I forgot to add the citation. Here's the bibtex and text:

Dumitrescu, S. D., Rebeja, P., Lorincz, B., Gaman, M., Avram, A., Ilie, M., Pruteanu, A., Stan, A., Rosia, L., Iacobescu, C., & others. (2021). Liro: Benchmark and leaderboard for romanian language tasks. Thirty-Fifth Conference on Neural Information Processing Systems Datasets and Benchmarks Track (Round 1).

@inproceedings{dumitrescu2021liro,
  title={Liro: Benchmark and leaderboard for romanian language tasks},
  author={Dumitrescu, Stefan Daniel and Rebeja, Petru and Lorincz, Beata and Gaman, Mihaela and Avram, Andrei and Ilie, Mihai and Pruteanu, Andrei and Stan, Adriana and Rosia, Lorena and Iacobescu, Cristina and others},
  booktitle={Thirty-fifth Conference on Neural Information Processing Systems Datasets and Benchmarks Track (Round 1)},
  year={2021}
}

Thank you very much!

**Comment by albertvillanova** [comment]
Thanks, @dumitrescustefan.

We have added that information to the Hugging Face Datasets library:
- https://github.com/huggingface/datasets/pull/4892
